apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-catalog-app
  template:
    metadata:
      labels:
        app: product-catalog-app
    spec:
      containers:
      - name: product-catalog-app-container
        image: lucassrg/alpha-office-product-catalog:latest
        imagePullPolicy: Always
        ports:
        - name: pc-app-port
          containerPort: 8085
          protocol: TCP
      imagePullSecrets:
        - name: ocir-twitter-feed-secret
---
apiVersion: v1
kind: Service
metadata:
  name: product-catalog-service
  labels:
    app: product-catalog-app
spec:
  ports:
  - port: 30000
    targetPort: 8085
  selector:
    app: product-catalog-app
  type: LoadBalancer
---

